In this lab, you will write a Python program to perform a very basic bioinformatics task: loading genetic information (in the form of DNA sequences) from a text file and computing how many times different amino acids appear in a corresponding protein.  You will develop the program step by step, adding more functionality as you go. The assignment has three parts, each of which corresponds to a task that the final program needs to solve:  Find the protein-coding part in a DNA sequence. Count the number of occurrences of each amino acid that appears in the protein. Load a DNA sequence from a file. Background. DNA carries the genetic instructions that organisms use to grow, survive, and reproduce. It is composed of two complementary strands, each made up of a sequence of four basic units called nucleotides: adenine (A), thymine (T), cytosine (C), and guanine (G). Since the two strands of DNA are complementary (A pairs with T, and C with G), knowing the sequence of one strand is enough to reconstruct the other. For this reason, we usually represent DNA using just one strand.  Within a DNA sequence, specific regions called genes encode proteins. Proteins are essential molecules in cells — they act as enzymes, form structures, send signals, and more. To build a protein from a DNA sequence, the sequence is read in consecutive triplets of nucleotides called codons. Each codon specifies one amino acid, the basic building block of proteins.  A protein can thus be thought of as a sequence of amino acids that is encoded by a stretch of DNA. While the exact sequence of amino acids determines a protein’s specific function, the overall composition — that is, how often each amino acid appears — is already of biological interest and can provide meaningful insights in various contexts. For example:  In genomics, researchers compare amino acid usage between species to study evolutionary relationships. Amino acid compositions are partly used to predict the function of a protein. In disease research, abnormal amino acid patterns can be linked to genetic disorders. The goal of this lab is to automate this counting process: write a program to count the amino acids appearing in a protein within a DNA segment.  General instructions. All the functions required for this lab must be written in a Python module named aminofreq (i.e., in a file called aminofreq.py). A ZIP archive lab1.zip Download lab1.zipis provided, containing material for testing your code. More specifically, it includes:  a folder named examples, containing FASTA files (a definition of the FASTA format is provided in Section 3); a Python script test.py, which serves as the test suite for automatically checking your functions. It is essential that you name and define the functions exactly as specified in the lab, so that they can be correctly recognized and tested by the test suite. The test suite can be run from the terminal/command line, like so:   on macOS/Linux $ python3 test.py on Windows $ python test.py The test suite can be executed at any time, even if not all functions have been implemented — the tests corresponding to missing functions will be skipped automatically.
1. Finding the protein-coding part in a DNA sequence
In this first part, you will write a program to extract the protein-coding part from a DNA segment. We first introduce the necessary notions to complete this task.

Start and Stop Codons. Recall that a codon is a sequence of three nucleotides. Among all codons, some are special: several codons (usually ATG) signal the start of a protein — these are called start codons — and several codons (e.g., TAA, TAG, or TGA) signal the end — these are called stop codons. The exact codon usage can vary slightly between species, but this general structure is consistent across almost all organisms. So, a protein is more precisely a sequence of amino acids that is encoded by a DNA segment starting from a start codon and ending at a stop codon.

Reading Frames. When reading a DNA segment, the codons can be grouped in three different ways, depending on where you start reading. These are called the three reading frames on the forward strand:

Frame 0 starts reading from the first nucleotide.
Frame 1 starts from the second.
Frame 2 starts from the third.
For example, consider the following segment: ATGAAATAG. It contains the following codons in each reading frame:

Frame 0: ATG, AAA, TAG
Frame 1: TGA, AAT, AG (the last one is not a complete codon and can therefore be dismissed)
Frame 2: GAA, ATA, G (as previously, the last one is not a complete codon and can be dismissed)
In many cases, only one of the three frames will actually contain a valid protein — that is, a region starting with a start codon and ending with a stop codon. But when given a DNA segment, we don’t necessarily know which frame contains the real protein (if any), so it’s common to check all three (as will be done here).

To find the protein-coding part in a DNA segment, we will break down the problem into two functions: the first will extract the complete sequence of codons in a given reading frame, and the second will extract from this sequence the subsequence corresponding to the first identified protein (if any).

Write a function codons_extract that takes:

a DNA segment (as an uppercase string), and
an integer (corresponding to the reading frame),
and returns the list of codons (each codon as an uppercase string) in the frame (incomplete codons should be discarded).

Shown below are example calls to the codons_extract function — as they would appear in the Python shell. Recall that when working in the Python shell, you should first import your module, which can be done like so:

>>> from aminofreq import *
>>> codons_extract('ATTATGGCACTGTAAGT',0)
['ATT','ATG','GCA','CTG','TAA']
>>> codons_extract('ATGGTTGCCTTAGCAGTGAG',1)
['TGG','TTG','CCT','TAG','CAG','TGA']
>>> codons_extract('GAATGGTGGTCATGAATTAGA',2)
['ATG','GTG','GTC','ATG','AAT','TAG']
Write a function protein_extract that takes:

a list of codons (each codon being an uppercase string),
a list of start codons (each codon being an uppercase string), and
a list of stop codons (each codon being an uppercase string),
and returns the list of codons (each codon as an uppercase string), starting with the first start codon found in the list and ending with the first stop codon that follows. If no such region exists, it should return an empty list.

Here are example calls to the protein_extract function.

>>> protein_extract(['ATT','ATG','GCA','CTG','TAA','CTA'],['ATG'],['TAA','TAG'])
['ATG','GCA','CTG','TAA'] 
>>> protein_extract(['TGG','TTG','CCT','TAG','CAG','TGA'],['ATG','TTG'],['TAA','TAG','TGA'])
['TTG','CCT','TAG']
>>> protein_extract(['CTA','ATG','GTG','GTC','ATG','AAT','TAG','GGT'],['GTG','ATG'],['TAG','TGA'])
['ATG','GTG','GTC','ATG','AAT','TAG']
>>> protein_extract(['GTG','GCC','TAG','TTG','ATG','TTA','TAG','CCT'],['ATG','GTG'],['TAA','TAG','TGA'])
['GTG','GCC','TAG']
>>> protein_extract(['GTT','ATG','TCC','GTA','ACT'],['ATG'],['TAA','TAG','TGA'])
[]
>>> protein_extract(['TGC','CAT','TGA','ATT'],['GTG'],['TAA','TAG','TGA'])
[]
>>> protein_extract(['TAA','CTT','GTG','GCT','TGC'],['GTG'],['TAA','TAG','TGA'])
[]

Hint. One possible approach to writing the protein_extract function is to first define a small helper function — that is, a separate function that performs one specific subtask. This function would take a list of codons and a list of patterns (for example, the start codons or the stop codons), and return the index of the first codon in the list matching one of these patterns. If no such element exists, it can return a value that clearly indicates this (for instance, -1). You could then use this helper function to find the position of the first start codon and the first stop codon that follows.

2. Counting amino acids in a protein
In this second part, you will write a program to count the number of occurrences of amino acids appearing in a protein. To achieve this, we first need to introduce the notion of a genetic code.

Genetic Code. As mentioned earlier, codons specify amino acids. A genetic code is a mapping from codons to amino acids: it defines how each codon is translated into an amino acid, or acts as a stop codon that signals the end of the protein. Within a genetic code, each codon is therefore either a stop codon or corresponds to exactly one amino acid. While there is a standard genetic code, slight variations exist between organisms — meaning that the same codon may translate to different amino acids in different genetic codes.

Because there are four nucleotides, there are 43 = 64 possible codons. Since there are only 20 amino acids, this means that a genetic code is redundant — multiple codons can correspond to the same amino acid. For example, in the standard genetic code, the codons TTT and TTC both code for the amino acid phenylalanine (abbreviated F).

We will represent a genetic code in Python as a dictionary where the keys are codons (as uppercase strings) and the values are the corresponding amino acids (as single-character uppercase strings). For example, the dictionary below represents the standard genetic code:

genetic_code = {'GCT':'A','GCC':'A','GCA':'A','GCG':'A', 
               'CGT':'R','CGC':'R','CGA':'R','CGG':'R','AGA':'R','AGG':'R', 
               'AAT':'N','AAC':'N', 
               'GAT':'D','GAC':'D', 
               'TGT':'C','TGC':'C', 
               'CAA':'Q','CAG':'Q', 
               'GAA':'E','GAG':'E', 
               'GGT':'G','GGC':'G','GGA':'G','GGG':'G', 
               'CAT':'H','CAC':'H', 
               'ATT':'I','ATC':'I','ATA':'I', 
               'CTT':'L','CTC':'L','CTA':'L','CTG':'L','TTA':'L','TTG':'L', 
               'AAA':'K','AAG':'K', 
               'ATG':'M', 
               'TTT':'F','TTC':'F', 
               'CCT':'P','CCC':'P','CCA':'P','CCG':'P', 
               'TCT':'S','TCC':'S','TCA':'S','TCG':'S','AGT':'S','AGC':'S', 
               'ACT':'T','ACC':'T','ACA':'T','ACG':'T', 
               'TGG':'W', 
               'TAT':'Y','TAC':'Y', 
               'GTT':'V','GTC':'V','GTA':'V','GTG':'V'}
Note that the only codons that do not appear in this dictionary are TTA, TAG, and TGA, which are the stop codons in the standard genetic code.  

When counting amino acids' occurrences in practice, we might not always want to use a complete genetic code. For instance:

We may only want to count occurrences of specific amino acids (e.g., phenylalanine 'F' and leucine 'L').
We may only want to count occurrences of amino acids encoded by specific codons (e.g., phenylalanine encoded by TTT but not by TTC).
The function you will write will allow such flexibility. 

Write a function aa_count that takes:

a list of codons (each codon being an uppercase string), and
a (partial) genetic code (as a dictionary),
and returns the number of occurrences of each amino acid encoded by a codon that appears both in the list and the (partial) genetic code taken as parameters. The result should be returned as a dictionary where the keys are amino acids (as single-character uppercase strings) and the values are their occurrence counts (as integers). 

Here are example calls to the aa_count function.

>>> aa_count(['ATG','GTG','GTC','TAG'], {'ATG':'M','TTT':'F','TTC':'F','GTC':'V','GTG':'V','AAC':'N','TAT':'Y'})
{'M':1,'V':2}
>>> aa_count(['ATG','GTG','GTC','TAG'], {'ATG':'M','TTT':'F','TTC':'F','GTG':'V','AAC':'N','TAT':'Y'})  
{'M':1,'V':1}
>>> aa_count(['ATG','TAG','GTC','TTT','TAG'], {'ATG':'M','TTT':'F','TTC':'F','GTC':'V','AAT':'N','AAC':'N','TAT':'Y'})
{'M':1,'V':1,'F':1}
>>> aa_count(['ATG','TAG','GTC','TTT','TAG'], {'TTC':'F','GTG':'V','AAT':'N','AAC':'N','TAT':'Y'})
{}
3. Loading a DNA sequence from a file
In this third part, you will write a program to load a specific DNA sequence from a file. To this end, we first introduce the FASTA format.

FASTA format. DNA sequences are commonly stored in a text file following a standard format called FASTA. In this format, each DNA segment is identified by a name (called an identifier) that appears on a line starting with the > character. The DNA sequence itself appears on the following lines — empty lines are ignored. Here’s an example of a FASTA file with two sequences:

>sequence1
ATGACATAGAGTGA
ATGGGATTGAATAA
CGTTA
>sequence2
atgcccattagtga
atgcata
To work with biological data, it’s important to be able to read sequences from such files. In the examples folder from the provided ZIP archive, you will find examples of FASTA files (including a real FASTA file).

Write a function read_dna that takes:

an identifier (as a string), and
the path to a FASTA file (as a string),
and returns the DNA sequence (as an uppercase string) associated with that identifier if present in the file (the empty string otherwise).

Here are example calls to the read_dna function using the FASTA file example1.fna from the provided ZIP archive.

>>> read_dna('sequence1','examples/example1.fna')
'ATGACATAGAGTGAATGGGATTGAATAACGTTA'
>>> read_dna('sequence2','examples/example1.fna')
'ATGCCCATTAGTGAATGCATA'
>>> read_dna('sequence3','examples/example1.fna')
''
4. The completed program
In this last part, you will combine the previous functions into a single function composition. This function takes:

an identifier (as a string),
the path to a FASTA file (as a string),
a (partial) genetic code (as a dictionary),
a list of start codons (each codon being an uppercase string), and
a list of stop codons (each codon being an uppercase string).
It should do the following.

Extract the corresponding DNA sequence from the file if present, print out the message "Error: the sequence is not in the file" otherwise.
For each of the three forward reading frames, look for a valid protein:
If none is found in the reading frame i, print out the message "Frame i: no valid protein".
Otherwise, print out the protein (as a list of codons) and the amino acid count (as a dictionary) — see example below for the exact format.
Here are example calls to the composition function using the dictionary genetic_code from Section 2 and the FASTA file example1.fna from the provided ZIP archive.

>>> composition('sequence1','examples/example1.fna',genetic_code,['ATG','GTG'],['TAG','TAA'])
Frame 0:
protein: ['ATG', 'ACA', 'TAG']
amino acid count: {'M': 1, 'T': 1}
Frame 1:
protein: ['GTG', 'AAT', 'GGG', 'ATT', 'GAA', 'TAA']
amino acid count: {'V': 1, 'N': 1, 'G': 1, 'I': 1, 'E': 1}
Frame 2: no valid protein
>>> composition('sequence3','examples/example1.fna',genetic_code,['ATG','GTG'],['TAG','TAA'])
Error: the sequence is not in the file